agentType: prometheus
type: exporter

name: oracle_collector_plugin
version: 1.0.0

category: 数据库

params:
  - oracle_server
  - oracle_port
  - oracle_username
  - oracle_password
  - oracle_remote_collect
  - oracle_sid
  - exporter_host
  - exporter_port
